" .vimrc
"
" Author: Benjamin Jones <benjaminfjones@gmail.com>
"         with help from many others
"

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Prelude

let $VIMHOME = $HOME . '/.vim'

" required for Vundle.vim
set nocompatible
filetype off

" Set the leader as ';' instead of '\'
let mapleader      = ";"
let maplocalleader = ";"


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugins (Vundle)

" set the runtime path to include Vundle.vim and initialize
set rtp+=$VIMHOME/bundle/Vundle.vim
call vundle#begin()

" Vundle
Plugin 'gmarik/Vundle.vim'

" The Pope
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'

" Vim Lion - quick alignment
"
" e.g,
"     glip=
"     3gLi(,
"     glip/-->
"     <visual>gl=
"
Plugin 'tommcdo/vim-lion'

" Tabular (better for code formatting)
Plugin 'godlygeek/tabular'
nmap <Leader>a= :Tabularize /=<CR>
vmap <Leader>a= :Tabularize /=<CR>
nmap <Leader>a: :Tabularize /:\zs<CR>
vmap <Leader>a: :Tabularize /:\zs<CR>
nmap <Leader>a, :Tabularize /,<CR>
vmap <Leader>a, :Tabularize /,<CR>

" Haskell
" Plugin 'elliottt/haskell-indent'
" Plugin 'elliottt/vim-haskell'

Plugin 'itchyny/lightline.vim'
set laststatus=2  " enable status line and message line
set noshowmode    " turn off redundant mode display
let g:lightline = {
      \  'active': {
      \    'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'relativepath' ] ],
      \    'right': [ [ 'percent', 'lineinfo' ], [ 'filetype' ] ]
      \  },
      \  'colorscheme': 'solarized'
      \}

" ctrl-p
Plugin 'kien/ctrlp.vim'
let g:ctrlp_map = '<space>'
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ --ignore "**/*.pyc"
      \ --ignore .cabal-sandbox
      \ --ignore .stack-work
      \ -g ""'
let g:ctrlp_cmd = 'CtrlP'
" let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_working_path_mode = 'w'
set wildignore+=*.o,*.hi,*/tmp/*,*.so,*.swp,*.zip,*.tgz,*.gz
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn|cabal\-sandbox|stack-work)$|[\/]dist$',
    \ 'file': '\v\.(exe|so|o|dll|dylib|a|hi)$',
    \ }
Plugin 'nixprime/cpsm'
let g:ctrlp_match_func = {'match': 'cpsm#CtrlPMatch'}

" Color scheme choices
Plugin 'altercation/vim-colors-solarized'

" QFEnter - open quickfix/loclist items in splits, tabs, etc..
Plugin 'yssl/QFEnter'
let g:qfenter_keymap = {}
let g:qfenter_keymap.open = ['<CR>']
let g:qfenter_keymap.vopen = ['<Leader>v']
let g:qfenter_keymap.hopen = ['<Leader>h']
let g:qfenter_keymap.topen = ['<Leader>t']

" vim-grepper : async grep/ag'ing for Vim 8 and NeoVim
Plugin 'mhinz/vim-grepper'
let g:grepper           = {}
let g:grepper.tools     = ['git', 'ag', 'grep']
let g:grepper.open      = 1
let g:grepper.jump      = 0
let g:grepper.next_tool = '<leader>g'
" The first two mappings open a prompt whereas the last one will search for
" the word under the cursor right away.
nnoremap <leader>git :Grepper -tool git -noswitch<cr>
nnoremap <leader>ag  :Grepper -tool ag  -grepprg ag --vimgrep -G '^.+\.txt'<cr>
nnoremap <leader>*   :Grepper -tool ag -cword -noprompt<cr>
nnoremap <leader>f   :Grepper -tool ag -cword -noprompt<cr>
command! -nargs=* AgFile Grepper -noprompt -tool ag -grepprg ag --vimgrep <args> %
command! -nargs=* Ag Grepper -noprompt -tool ag -grepprg ag --vimgrep <args>

" Tmux integration
Plugin 'benmills/vimux'

" ALE
Plugin 'w0rp/ale'
let g:ale_linters_explicit = 1
let g:ale_linters = {
\   'python': ['flake8', 'mypy'],
\}


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Post-plugin options
"
" All Plugins must be added before the following line
call vundle#end()

" Enable filetype detection
filetype plugin indent on

set ttyfast
set lazyredraw

set ignorecase smartcase

" Allow backspacing over everything
set backspace=indent,eol,start

" Incremental searching
set incsearch

" Cursor context
set scrolloff=3

" Always show cursor position
set ruler

" Fold by manually defined folds
set nofoldenable

" Syntax
if &t_Co > 2 || has("gui_running")
    syntax enable
    set hlsearch
endif

" Spell checking
if has("spell")
    setlocal spell spelllang=en_us
    set nospell
endif

" set text wrap width
set textwidth=78

" Highlight trailing space, and tab characters
set list lcs=tab:>-,trail:.

" Completion options
set wildmode=longest:full,list:full
set wildmenu
set wildignore=*.o,*.hi,*.swp,*.bc

" Colors!
set background=dark
colorscheme solarized

" reset highlighting
highlight Normal cterm=NONE ctermbg=NONE
highlight SignColumn ctermbg=Black

" Grey cursor line/col highlights
highlight CursorLine   term=bold cterm=bold guibg=Grey40
highlight CursorColumn term=bold cterm=bold guibg=Grey40

" Swap files in one place
set directory=$VIMHOME/swap

" Disable the bell
set noerrorbells
set visualbell
set t_vb=

" Always expand tabs to spaces
set expandtab
set tabstop=4

" Row/Column accents
set nocursorcolumn
set nocursorline
set nonumber
set norelativenumber


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" TABS

" Tab/buffer navigation via elliott
function! Next()
    if tabpagenr('$') > 1
        tabnext
    else
        bnext
    endif
endfunction

function! Prev()
    if tabpagenr('$') > 1
        tabprevious
    else
        bprevious
    endif
endfunction

nnoremap <silent> <C-n> :call Next()<Cr>
nnoremap <silent> <C-p> :call Prev()<Cr>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" macros

" create markdown style header below current line
let @h = "yypVr"
" format current selection
let @q = "{!}fmt"


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" NORMAL mode mappings

" Define double <leader> to kill the search highlighting.
nnoremap <Leader><Leader> :noh<Enter>
" set cursorline
nnoremap <Leader>c :set cursorcolumn!<CR>
nnoremap <Leader>C :set cursorline!<CR>
" move current line down
nnoremap - ddp
" move current line up
nnoremap <underscore> ddP
" uppercase the current word, put cursor after last char
nnoremap <c-u> viwUea
" edit $VIMRC in a split
nnoremap <Leader>ev :vsplit $MYVIMRC<CR>
" source $VIMRC
nnoremap <Leader>sv :source $MYVIMRC<CR>

" Disable the help key
nnoremap <F1> <Esc>
" Set F2 as the binding to toggle the paste mode
set pastetoggle=<F2>
" Use F3 to toggle spelling
nnoremap <F3> :set spell!<CR>
" remove trailing whitespace
nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" INSERT mode mappings

" Disable the help key
inoremap <F1> <Esc>
" jk trick!
inoremap jk <Esc>
" Crtl-d to delete current line
inoremap <c-d> <ESC>ddi
" uppercase current word, put cursor back insert mode after last char
inoremap <c-u> <ESC>viwUea

" Disable the arrow keys when in edit mode
inoremap <Up>    <NOP>
inoremap <Right> <NOP>
inoremap <Down>  <NOP>
inoremap <Left>  <NOP>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Abbreviations

iabbrev @@ benjaminfjones@gmail.com
iabbrev adn and
iabbrev waht what
iabbrev tehn then
