
# site-wide settings
if [[ -f /etc/zshrc ]]; then
  . /etc/zshrc
fi

# history
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt inc_append_history

# local functions
fpath=($fpath ~/.zsh/functions)

# emacs key bindings
bindkey -e

bindkey "^f" forward-word
bindkey "^b" backward-word

# completion
autoload -U compinit colors promptinit spectrum
compinit
colors
spectrum
promptinit

export EDITOR=vim

topit() { /usr/bin/top -p `pgrep $1` }
vimfind() { find -name $1 -exec vim -p {} + }

if [[ $TERM == "dumb" ]] ; then
  alias ls='ls --color=none'
else
  # colored tab-completion
  zstyle -e ':completion:*:default' list-colors 'reply=("${(@s.:.)LS_COLORS}")'
fi

if [[ $TERM == "xterm" ]] ; then
  export TERM="xterm-256color"
fi

# cabal completion
compdef -a _cabal cabal

# load in local config, if available
DARWIN=`uname -a | grep Darwin`
if [ -z $DARWIN ]; then
  echo Loading linux configuration
  if [[ -f ~/.zsh/linux-config ]]; then
    . ~/.zsh/linux-config
  fi
else
  echo Loading OS X configuration
  if [[ -f ~/.zsh/osx-config ]]; then
    . ~/.zsh/osx-config
  fi
fi

# Aliases
alias rm='rm -v'
alias vim='vim -p'
alias vi='vim -p'

## git aliases
alias gcm='git commit -m'
alias gits='git status'

## Cabal
alias ghc-sandbox="ghc -no-user-package-db \
                       -package-db .cabal-sandbox/*-packages.conf.d"
alias ghci-sandbox="ghci -no-user-package-db \
                         -package-db .cabal-sandbox/*-packages.conf.d"
alias runhaskell-sandbox="runhaskell -no-user-package-db \
                                     -package-db .cabal-sandbox/*-packages.conf.d"

## python
alias py='python'
alias ipy='ipython'
alias pyserve='python -m SimpleHTTPServer'

## sage aliases
alias mysage='~/sage/latest/sage'

## unison
alias uab='unison -auto -batch'

## misc
alias l.='ls -la .'
alias ll='ls -l'
alias la='ls -la'
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias fn='find . -name $@'

# Custom PATH additions
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/local/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export MANPATH=/usr/share/man:/usr/local/share/man:$MANPATH

export UNISONLOCALHOSTNAME=omicron.galois.com

### OH _ MY _ ZSH ###

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="blinks"
#ZSH_THEME="random"
#ZSH_THEME="mrtazz"
#ZSH_THEME="terminalparty"
ZSH_THEME=ys

export UPDATE_ZSH_DAYS=30

# disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# plugins
plugins=(git cabal brew pass)

source $ZSH/oh-my-zsh.sh

# disable auto correction
unsetopt correct
unsetopt correct_all

# local zshrc
if [ -f $HOME/.zshrc_local ]; then
    source $HOME/.zshrc_local
fi
